
function gwtau_embed_all()
%Plots embedding of GW-tau distances, using multidimensional scaling. The
%data points are color-coded according to their folder


%%% Sample code to compute GWtau distance matrix 
%%% This code uses (as an example) data from Ignacio et al. 2022
%%% In general, there are two possible cases for storing thetrajectories:
%%% (1) Trajectories have the same length: store as matrix (the case here)
%%% (2) Trajectories have different lengths: store as list 

%%% For Ignacio et al. 2022, all trajectroies are defined on the same time
%%% poitns, so we are at case (1)

%%% To compute the entry of GWtau matrix, 2 functions must be used:
%%% (1) vi=vec_geo_dist(Traji) computes vector of intrinsic distances along a
%%% trajectory Traji
%%% (2) wass_sorted(vi, vj) computes GWtau_ij, the GWtau distance between
%%% trajectories using their intrinsic distances

%%% 6 figures are generated by this code: 3 figures for plotting the data and 3 figures
%%% for plotting distance matrices



    %Getting paths from data folder
        allDataFolders=genpath("data");
        dataFolderList = strsplit(allDataFolders, pathsep);
        
        class_count=0; %keep track of number of datum in each folder
        key={}; %keep track of file names for legend of plots
    
        %Initialization
        tirotr_all=[];
        tirefr_all=[];
        tirotb_all=[];
        tirefb_all=[];

        cumFileNames={};

        %Iterating through folder paths
        for i = 1:length(dataFolderList)
            dataFolderPath = dataFolderList{i};
            
            if isempty(dataFolderPath)
                continue; %continue passes to next iteration of loop
            end
            
            % Get data files in this folder only (non-recursive)
            data_files_all = dir(fullfile(dataFolderPath, '*data.mat'));
    
            if isempty(data_files_all)
                continue;
            end
            
            folders=strsplit(dataFolderPath,filesep);
            name=folders{end};
            key{end+1}=name;
        
            %files=dir('15.png');
            filenames={}; %Storing filenames within folder
            for file=data_files_all'
               load(fullfile(dataFolderPath,file.name), "TIrotr","TIrefr","TIrotb","TIrefb");
               filenames{end+1}=erase(file.name,'_data.mat');
               tirotr_all(end+1,:)=TIrotr;
               tirefr_all(end+1,:)=TIrefr;
               tirotb_all(end+1,:)=TIrotb;
               tirefb_all(end+1,:)=TIrefb;
            end
            cumFileNames=[cumFileNames,filenames];

            %Keep track of number of datum in each file
            class_count(end+1)=length(data_files_all);
    
        end %End loop through data folders
    
    %Save TI

    filePath='gwtau_plots';
        
        if ~exist(filePath,"dir")
            mkdir(filePath)
        end

    save(fullfile(filePath,'data.mat'), 'tirotr_all','tirefr_all','tirotb_all','tirefb_all');
    
    %load tirefr.mat
    %X=tirefr_all';
    %X=[wt gpb1 let99]; %stores all trajectories in a matrix X

    %Computing GW-tau for all transformations and centers
    iterations={tirotr_all',tirefr_all',tirotb_all',tirefb_all'};

    for l=1:4
        X=iterations{l};
    
        %Each column is an image, rows represent theta mesh points
        n=size(X,2); %number of trajectories in the dataset (all distance matrices will thus be n-by-n)
        
        %%% GWtau
        GW=zeros(n,n); %initialize GWtau distance matrix
        n_time_pts=size(X,1); %number of time/theta points (the same for all trajectories)
        time=(0:n_time_pts-1)';
        for i=1:n
            for j=i+1:n %since GWtau is symmetric matrix, we only compute it's upper part
                timei=time; %define time vector (is the same for all trajectories in this case)
                timej=time;
                Traji=[timei X(:,i)]; %extract trajectory i as 2-coordinate object: [time measurements]
                Trajj=[timej X(:,j)]; %extract trajectory j as 2-coordinate object: [time measurements]
                vi=vec_geo_dist(Traji); %compute vector of intrinsic distances from the start of trajectory i
                vj=vec_geo_dist(Trajj); %compute vector of intrinsic distances from the start of trajectory j
                GW(i,j)=wass_sorted(vi,vj); %compute GWtau as wasserstein distance
            end
        end
    
        %Add transpose to get full distance matrix from the upper triangular
        %one computed
        GW=GW+GW';  
        
        %D=GW;
        % num_clusters = 2;
        % Step 1: Non-Metric MDS (like isoMDS)
        [XMDS_GW, ~] = mdscale(GW, 2); 

        class_num=length(class_count)-1;
        sz=50; %size of points in scatter plot
        colors=lines(class_num); %creating rgb color for each class

        
        
        %%%%%%%%%%% heatmap GW
        h1=figure('Visible','Off');
        heatmap(GW,'Colormap',cool);
        title('GWtau')
    
        h2=figure('Visible','Off');
        for class=1:class_num
            %Remember that class_count contains 0 as first component
            rws=sum(class_count(1:class))+1:sum(class_count(1:class+1));
            scatter(XMDS_GW(rws,1), XMDS_GW(rws,2), sz, colors(class,:), 'filled');
            hold on
        end
        hold off
        legend(key,'Interpreter','none');
        title('Non-Metric MDS Colored by Class');
        xlabel('Dimension 1'); ylabel('Dimension 2');
        grid on;



        %%Save figures to appropriate folders

        
        
        %Naming depends on loop
        if l==1
            %Add GW matrix to data file
            tirotr_XMDS=XMDS_GW;
            save(fullfile(filePath,'data.mat'),'tirotr_XMDS','-append')
            exportgraphics(h1,fullfile(filePath,"tirotr_dist.jpg"));
            exportgraphics(h2,fullfile(filePath,"tirotr_plot.jpg"));
            savefig(h2,fullfile(filePath,"tirotr_plot.fig"));
        elseif l==2
            %Add GW matrix to data file
            tirefr_XMDS=XMDS_GW;
            save(fullfile(filePath,'data.mat'),'tirefr_XMDS','-append')
            exportgraphics(h1,fullfile(filePath,"tirefr_dist.jpg"));
            exportgraphics(h2,fullfile(filePath,"tirefr_plot.jpg"));
            savefig(h2,fullfile(filePath,"tirefr_plot.fig"));
        elseif l==3
            %Add GW matrix to data file
            tirotb_XMDS=XMDS_GW;
            save(fullfile(filePath,'data.mat'),'tirotb_XMDS','-append')
            exportgraphics(h1,fullfile(filePath,"tirotb_dist.jpg"));
            exportgraphics(h2,fullfile(filePath,"tirotb_plot.jpg"));
            savefig(h2,fullfile(filePath,"tirotb_plot.fig"));
        elseif l==4
            %Add GW matrix to data file
            tirefb_XMDS=XMDS_GW;
            save(fullfile(filePath,'data.mat'),'tirefb_XMDS','-append')
            exportgraphics(h1,fullfile(filePath,"tirefb_dist.jpg"));
            exportgraphics(h2,fullfile(filePath,"tirefb_plot.jpg"));
            savefig(h2,fullfile(filePath,"tirefb_plot.fig"));
        end


    end %end iterations through different transformations and centers

    


end %end function



