
function gwtau_embedding(TI_trans)

    %Arguments
    %   TI_trans: a string either 'tirotr', 'tirefr', 'tirotb', or 'tirefb'
    %   describing choices for the TI curves that you wish to compare
    %       tirotr: Compare TI by rotation for the rotational center
    %       tirefr: Compare TI by reflection for the rotational center
    %       tirotb: Compare TI by rotation for the reflectional center
    %       tirefb: Compare TI by reflection for the reflectional center


%%% Sample code to compute GWtau distance matrix 
%%% This code uses (as an example) data from Ignacio et al. 2022
%%% In general, there are two possible cases for storing thetrajectories:
%%% (1) Trajectories have the same length: store as matrix (the case here)
%%% (2) Trajectories have different lengths: store as list 

%%% For Ignacio et al. 2022, all trajectroies are defined on the same time
%%% poitns, so we are at case (1)

%%% To compute the entry of GWtau matrix, 2 functions must be used:
%%% (1) vi=vec_geo_dist(Traji) computes vector of intrinsic distances along a
%%% trajectory Traji
%%% (2) wass_sorted(vi, vj) computes GWtau_ij, the GWtau distance between
%%% trajectories using their intrinsic distances

%%% 6 figures are generated by this code: 3 figures for plotting the data and 3 figures
%%% for plotting distance matrices



    %Getting paths from data folder
        allDataFolders=genpath("data");
        dataFolderList = strsplit(allDataFolders, pathsep);
    
        %Iterating through folder paths)
        for i = 1:length(dataFolderList)
            dataFolderPath = dataFolderList{i};
            
            if isempty(dataFolderPath)
                continue; %continue passes to next iteration of loop
            end
        
            % Get data files in this folder only (non-recursive)
            data_files_all = dir(fullfile(dataFolderPath, '*data.mat'));
    
            if isempty(data_files_all)
                continue;
            end
        
            %files=dir('15.png');
            file_count_all=1;
        
            for file=data_files_all'
               load(fullfile(dataFolderPath,file.name), "TIrotr","TIrefr","TIrotb","TIrefb");
               tirotr_all(file_count_all,:)=TIrotr;
               tirefr_all(file_count_all,:)=TIrefr;
               tirotb_all(file_count_all,:)=TIrotb;
               tirefb_all(file_count_all,:)=TIrefb;
               file_count_all=file_count_all+1;
            end
    
        end

    %Based on user input, select the appropriate TI curves
    %Taking transpose so that columns are a flower and rows are angles of
    %rotation for the TI curve
    if strcmp(TI_trans,'tirotr')
        X=tirotr_all';
    elseif strcmp(TI_trans,'tirefr')
        X=tirefr_all';
    elseif strcmp(TI_trans,'tirotb')
        X=tirefb_all';
    elseif strcmp(TI_trans,'tirefb')
        X=tirefb_all';
    else
        error("must input one of the following strings: 'tirotr', 'tirefr, 'tirotb', 'tirefb'");
        return
    end %End conditional statements
    
    %load tirefr.mat
    %X=tirefr_all';
    %X=[wt gpb1 let99]; %stores all trajectories in a matrix X
    
    
    
    n=size(X,2); %number of trajectories in the dataset (all distance matrices will thus be n-by-n)
    
    %%% GWtau
    GW=zeros(n,n); %initialize GWtau distance matrix
    n_time_pts=size(X,1); %number of time/theta points (the same for all trajectories)
    time=(0:n_time_pts-1)';
    for i=1:n
        for j=i+1:n %since GWtau is symmetric matrix, we only compute it's upper part
            timei=time; %define time vector (is the same for all trajectories in this case)
            timej=time;
            Traji=[timei X(:,i)]; %extract trajectory i as 2-coordinate object: [time measurements]
            Trajj=[timej X(:,j)]; %extract trajectory j as 2-coordinate object: [time measurements]
            vi=vec_geo_dist(Traji); %compute vector of intrinsic distances from the start of trajectory i
            vj=vec_geo_dist(Trajj); %compute vector of intrinsic distances from the start of trajectory j
            GW(i,j)=wass_sorted(vi,vj); %compute GWtau as wasserstein distance
        end
    end

    %Add transpose to get full distance matrix from the upper triangular
    %one computed
    GW=GW+GW';  
    
    %Dynamic time warping and Euclidean distance btwn TI curves
    % %%% Dynamic time warping (using Matlab's function 'dtw')
    % DTW=zeros(n,n);
    % for i=1:n
    %     for j=1:n
    %         DTW(i,j)=dtw(X(:,i),X(:,j));
    %     end
    % end
    % 
    % %%% Euclidean
    % E=zeros(n,n);
    % for i=1:n
    %     for j=i+1:n
    %         timei=(0:n_time_pts-1)';
    %         timej=(0:n_time_pts-1)';
    %         Traji=[timei X(:,i)];
    %         Trajj=[timej X(:,j)];
    %         E(i,j)=norm(Traji-Trajj);
    %     end
    % end
    % E=E+E';
    
    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% plots
    %%% plot the trajectories
    % figure(1)
    % plot(wt,'g')
    % ylim([-80 80])
    % xlabel('time')
    % ylabel('measurement')
    % title('wt trajectories')
    % figure(2)
    % plot(gpb1,'m')
    % ylim([-80 80])
    % xlabel('time')
    % ylabel('measurement')
    % title('gpb-1 trajectories')
    % figure(3)
    % plot(let99,'m')
    % ylim([-80 80])
    % xlabel('time')
    % ylabel('measurement')
    % title('let-99 trajectories')
    
    %%%%plot distances and the embedding
    % img1 = imread('374.png');
    % img2 = imread('377.png');
    % img3 = imread('378.png');
    % img4 = imread('379.png');
    % img5 = imread('382.png');
    % img6 = imread('383.png');
    
    % figure(1)
    % subplot(1,6,1)
    % imshow(img1); 
    % subplot(1,6,2)
    % imshow(img2); 
    % subplot(1,6,3)
    % imshow(img3); 
    % subplot(1,6,4)
    % imshow(img4); 
    % subplot(1,6,5)
    % imshow(img5); 
    % subplot(1,6,6)
    % imshow(img6); 
    
    %D=GW;
    num_clusters = 2;
    % Step 1: Non-Metric MDS (like isoMDS)
    [XMDS_GW, ~] = mdscale(GW, 2, 'Criterion', 'sstress'); 
    % [XMDS_E, stress] = mdscale(E, 2, 'Criterion', 'sstress'); 
    % [XMDS_DTW, stress] = mdscale(DTW, 2, 'Criterion', 'sstress'); 
    
    % Step 2: Perform K-Means Clustering (k=3, as in R)
    cluster_labels_GW = kmeans(XMDS_GW, num_clusters);
    % cluster_labels_E = kmeans(XMDS_E, num_clusters);
    % cluster_labels_DTW = kmeans(XMDS_DTW, num_clusters);
    
    
    %%%%%%%%%%% heatmap GW
    h1=figure('Visible','Off');
    heatmap(GW,'Colormap',cool);
    title('GWtau')

    h2=figure('Visible','Off');
    scatter(XMDS_GW(:,1), XMDS_GW(:,2), 50, cluster_labels_GW, 'filled');
    text(XMDS_GW(:,1), XMDS_GW(:,2), cellstr(num2str((1:size(GW,1))')), 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
    title('Non-Metric MDS with K-Means Clustering');
    xlabel('Dimension 1'); ylabel('Dimension 2');
    grid on;
    
    % %%%%%%%%%%% heatmap DTW
    % figure(3)
    % subplot(1,2,1)
    % heatmap(DTW,'Colormap',cool)
    % title('Dynamic Time Warping (DTW)')
    % subplot(1,2,2)
    % scatter(XMDS_DTW(:,1), XMDS_DTW(:,2), 50, cluster_labels_DTW, 'filled');
    % text(XMDS_DTW(:,1), XMDS_DTW(:,2), cellstr(num2str((1:size(DTW,1))')), 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
    % title('Non-Metric MDS with K-Means Clustering');
    % xlabel('Dimension 1'); ylabel('Dimension 2');
    % grid on;
    % 
    % %%%%%%%%%%% heatmap Euclidean
    % figure(4)
    % subplot(1,2,1)
    % heatmap(E,'Colormap',cool)
    % title('Euclidean')
    % subplot(1,2,2)
    % scatter(XMDS_E(:,1), XMDS_E(:,2), 50, cluster_labels_E, 'filled');
    % text(XMDS_E(:,1), XMDS_E(:,2), cellstr(num2str((1:size(E,1))')), 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
    % title('Non-Metric MDS with K-Means Clustering');
    % xlabel('Dimension 1'); ylabel('Dimension 2');
    % grid on;
    
    %%%%%%%%Embedding using MDS
    
    % % Step 3: Plot results
    % figure(7)
    % scatter(XMDS(:,1), XMDS(:,2), 50, cluster_labels, 'filled');
    % text(XMDS(:,1), XMDS(:,2), cellstr(num2str((1:size(D,1))')), 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
    % title('Non-Metric MDS with K-Means Clustering');
    % xlabel('Dimension 1'); ylabel('Dimension 2');
    % grid on;


    %%Save figures to appropriate folders

   
    filePath='gwtau_plots';
    
    if ~exist(filePath,"dir")
        mkdir(filePath)
    end

    exportgraphics(h1,fullfile(filePath,"dist_matrix.jpg"));
    exportgraphics(h2,fullfile(filePath,"scatter_plot.jpg"));


end



