% %Gets user inputs and completes data analysis

clear
 
% topFolder=input(['Input the path to the image top folder relative to the matlab files\n'...
%     'For example, our repository/folder has the structure\n'...
%     'repo/\n'...
%     '|--TransInfo_angiosperms.m\n'...
%     '|--transinfo.m\n'...
%     '...\n'...
%     '|--angiosperms\n'...
%     '...\n'...
%     'where all of our flower images are contained in the angiosperms folder\n'...
%     'and are classified with subfolders.\n'...
%     'We would input "angiosperms" (without quotes).\n'...
%     'Image folder: '],'s');
% 
% 
% TransInfo_images(topFolder);
% 
% class_pca();


ti_pca_all();


% allFolders=genpath("data");
% folderList = strsplit(allFolders, pathsep);
% relativePath=folderList{1};
% parts=split(relativePath,filesep);
% topFolder=parts{1}; %Get name of top folder (should be "data")
% 
% folderPath=folderList{2};
% files = dir(fullfile(folderPath, '*data.mat'));

